### ISSUE TITLE
presentation not working on stim computer

### ISSUE THREAD

**Issue by mbolding** [mbolding/cinl#108]
see error note in log book

**Comment by mbolding** [comment]
same as #5 
`invalid partition table`

**Comment by mbolding** [comment]
- switch to the other computer. and see if problem recurs.
- rename the computers to something other than stim and data acq.  it is confusing. call them Ren and Stimpy.
- Mason will reinstall Presentation and move the parallel port card. 
- we will tell Dell they need to send a whole new computer.

**Comment by MegaRich** [comment]
Computer is now working, switched the hard drive cable. 
it needs to be copied asap.

**Comment by mbolding** [comment]
use this http://www.macrium.com/reflectfree.aspx

**Comment by mbolding** [comment]
closed for now except for cloning
