### ISSUE TITLE
Can we push scans to the CIMS server?

### ISSUE THREAD

**Issue by brentwomble** [mbolding/cinl#120]

**Comment by mbolding** [comment]
emailed Chris Price..

**Comment by mbolding** [comment]
got instructions from Chris, tested, works, need to add the location to CINL_OSIRIX

**Comment by brentwomble** [comment]
Is this something we do on Osirix? I didn't see a CIMS destination on the scanner console

**Comment by mbolding** [comment]
You have to add the destination to CINL_OSIRIX.  We are not adding it to the scanner.   You will need to push to OSIRIX first.

**Comment by brentwomble** [comment]
How do I add the destination to CINL_OSIRIX?

**Comment by brentwomble** [comment]
For reference:

CINL_OSIRIX and CIMS are both on the hospital network. I was able to access the CIMS patient browser ([http://image.hs.uab.edu:8080/search.html](http://image.hs.uab.edu:8080/search.html)) on the Mac that runs  CINL_OSIRIX.

**Comment by brentwomble** [comment]
I added CIMS as a destination on CINL_OSIRIX, and I was able to push scans successfully.

I found the scans I pushed in the CIMS study browser. Next step is to try to pull scans off CIMS. After that, I'll close the ticket.

**Comment by brentwomble** [comment]
For future reference:

To push research data to CIMS, you just need to build the CIMS archive into OSIRIX with AE Title of AETitle1, IP of 10.210.6.224 and Port of 104.  Once the patient is in OSIRIX, just click Send and make sure CIMS is chosen as the destination.  I will be glad to help set this up if there is anything that you need.

Chris
