### ISSUE TITLE
How to get physio data data off scanner 

### ISSUE THREAD

**Issue by mbolding** [mbolding/cinl#125]
https://www.google.com/search?q=How+to+save+the+Siemens+Physiologic+Monitoring+Unit+(PMU)+data+to+a+file

**Comment by mbolding** [comment]
I think I found it here too. https://cfn.upenn.edu/aguirre/wiki/public:pulse-oximetry_during_fmri_scanning

**Comment by mbolding** [comment]
Will confirm with Nouha

**Comment by mbolding** [comment]
solved

**Comment by jtotenha** [comment]
turns out the upenn method does not work with the Prisma's software, attached is the correct method to use (also on slack in docs-and-methods)
[prisma_physiologging.pdf](https://github.com/mbolding/cinl/files/298381/prisma_physiologging.pdf)
