### ISSUE TITLE
need printed instructions for resetting patient table error in control room

### ISSUE THREAD

**Issue by mbolding** [mbolding/cinl#144]

**Comment by jtotenha** [comment]
I think this may be the reset stop button on the intercom, see excerpt from system manual: 
![intercom](https://cloud.githubusercontent.com/assets/19213072/19005418/2803ebfe-8720-11e6-9445-e7c3b43da751.jpg)

**Comment by jtotenha** [comment]
I think button #7 on the intercom will clear the table error that you get when you hit button #1 on the intercom, need to test to make sure
