### ISSUE TITLE
shimming problem w/ EPSI, 9/19/2016

### ISSUE THREAD

**Issue by jtotenha** [mbolding/cinl#181]
could be related to prior shimming issues (6/16/16), issue #129 

intermittent, not sure of any pattern, Taub lab is using similar EPSI sequences

**Comment by jtotenha** [comment]
still a problem, 9/23

**Comment by jtotenha** [comment]
not consistent, possibly related to participant's dental work? related to time of day, gradients' recent use?

need to test somehow

**Comment by brentwomble** [comment]
The Taub lab has noticed that the shimming issue gets worse if 2 EPSI sequences are run back-to-back. 
Maybe it's related to SAR or the temperature of the gradients?

**Comment by jtotenha** [comment]
could test the back-to-back EPSI shimming performance with phantoms, see if it gets worse on subsequent scans

**Comment by jlin137** [comment]
On Sunday, we ran 2 EPSI scans back-to-back and the shims were 16.8 and 16.4, respectively
