### ISSUE TITLE
shimming problem w/ SVS hippocampus

### ISSUE THREAD

**Issue by jtotenha** [mbolding/cinl#184]
shimming take 5-7 minutes to get acceptable values of fwhm and t2*, used to take no time at all

possibly related to shimming issues #181, #129

**Comment by mbolding** [comment]
Dr. Bolding,

Thanks for looking into this for us. After chatting with David and Dr. Lahti yesterday, it seems that we often have trouble with the scans after running the MPFC Megapress sequence. I wanted to let you know in case there was any significance. And of course, we are more than happy to remove this sequence from the protocol if it is indeed causing a problem.

Thanks,
