### ISSUE TITLE
possible abnormal shimming behavior during GRE fieldmap scans

### ISSUE THREAD

**Issue by jtotenha** [mbolding/cinl#188]
prescan adjusments seem to be taking longer than usual, displays frequency adjust - 3d shim - frequency adjust - 3d shim - frequency adjust

does  this usually take so long and repeat the freq-shim-freq cycle so many times?

**Comment by jtotenha** [comment]
is this related to the shimming issues with the SVS and CSI?

is this something that will be checked during the PM visit?

**Comment by mbolding** [comment]
Dr. Bolding,

Thanks for looking into this for us. After chatting with David and Dr. Lahti yesterday, it seems that we often have trouble with the scans after running the MPFC Megapress sequence. I wanted to let you know in case there was any significance. And of course, we are more than happy to remove this sequence from the protocol if it is indeed causing a problem.

Thanks,

**Comment by jtotenha** [comment]
probably related to the "advanced shim" mode used in EPI scans,

this is found in the protocols under the system tab, adjustments, shim mode

see the following from UC Berkeley's MRI center:
https://practicalfmri.blogspot.com/2013/03/quick-update-for-siemens-users.html
