### ISSUE TITLE
keep running out of disk space on scanner even when deleting > 2 week old data.

### ISSUE THREAD

**Issue by mbolding** [mbolding/cinl#197]

**Comment by jtotenha** [comment]
a major culprit seems to be EPSI scans, a commonly used version generates datafiles of 29MB each when exported, one lab uses 576 of these per scan (~16.3GB), another lab uses 720 (~20.4GB)

I made a note that the database was 66% full, then deleted a single scan of the 16.3GB type, the database dropped to 60%

based on this, I'd estimate that the database can hold ~272GB, so it doesn't take very many EPSI scans to fill it up

the EPSI scans cannot be stored on CINL_OSIRIX and are being exported to USB drive by users as they scan, could we ask users to delete them from the database after they've put them onto USB drive?  

Or should the EPSI data have a more limited time to reside on the scanner apart from the 2 weeks that images have been given?

**Comment by mbolding** [comment]
lets ask users to remove them after they have copied them to a USB drive.

**Comment by jlin137** [comment]
Can we at least have a few days (up to a week perhaps?) so that we can be sure that the data transferred correctly, and we get a backup to our own lab servers before we delete the only original copy?

**Comment by mbolding** [comment]
a week is fine for now.    we need a long term solution.  the long term solution may be setting up XNAT.

Best Regards,

Mark Bolding, PhD
University of Alabama at Birmingham
Assistant Professor, Departments of Radiology, Vision Sciences, and Neurobiology
Director, Civitan International Neuroimaging Laboratory
Co-Director, UAB Small Animal Imaging Shared Facility
Associate Director, UAB Comprehensive Neuroscience Center
