### ISSUE TITLE
image recon issues with multi band DWI

### ISSUE THREAD

**Issue by mbolding** [mbolding/cinl#2]
mb epi sequences crash the image recon system

**Comment by mbolding** [comment]
need to rerun janes protocol

**Comment by mbolding** [comment]
need to add 32 dir standard DTI to protocol

**Comment by mbolding** [comment]
![img_20160504_185251](https://cloud.githubusercontent.com/assets/157241/15032783/198dfbc0-122a-11e6-9cf4-b619e7078904.jpg)

**Comment by mbolding** [comment]
- MB DWI causes image recon fail
- after this you cant run any other scans
- that can be fixed by restating the MrIrisContainer uder meas and recon tab under system manager
- trying to run MB DWI again causes the error to repeat.
- turning off ICE does not help
- logged as issue #2
- reinstalling the MB EPI software did not fix
- sent email to Essa Yacoub

**Comment by mbolding** [comment]
- error continues after reboot
- cmrr_mbep2d_diff fails but _bold does not
- the protocol and log files sent to Essa Yacoub

**Comment by mbolding** [comment]
need to try phoenix import of one that worked before

**Comment by mbolding** [comment]
Qs
- any post-processing options are turned off ? DTI, etc. 
- there are more than 6 directions

As
- Online multi-band recon is set to ‘online'
- DOT add in is set to <empty> 
- under diff neuro Diff. weighted images and Mosaic are checked, everything else is off.
- there are 98 directions

**Comment by mbolding** [comment]
- phoenix import failed to resolve the issue. so what worked before does not work now. 
- bold works, so something about the ICE environment?  time to start digging in the log files.

**Comment by mbolding** [comment]
found this in the logs (imagereconstruction.utr).  not sure if it is helpful.

`102|2016/05/07-09:50:13.887784|mars|18961|MrIrisContainer|19108|MrParcIF-DispThread|731|Error|DLL|1|ICE.CMRR_MBIcePrg2D|MrServers|CMRR_MBIcePrg2D|/vobs/n4/pkg/MrServers/MrImaging/Ice/CMRR_MBIcePrg2D/../ejaIcePrg2D/ejaMBCalcGRAPPA.cpp|211|ejaMBCalcGRAPPA::EndInit(env)|54904|0||ejaMBCalcGRAPPA: Instance 1 failed to get device handle for GPU device 1): ret = 101 status = 0xc0000001
`

**Comment by mbolding** [comment]
tried sending mail to remote service through the configuration window.  Probably have to call too.

**Comment by mbolding** [comment]
Cinl00229 was used for the Phoenix import. did not work.

**Comment by BrennanHickson** [comment]
I'm not sure if [this document](https://www.cmrr.umn.edu/multiband/Multi-Band_C2P_Instructions_R013a.pdf) is relevant to this issue, but I thought I'd post it just in case. This advice from page 17 seems to refer to the overarching issue that we've experienced:

> Image reconstruction should no longer fail at the start of a scan if an Image Numbering scheme (defined on System/Miscellaneous card) other than the default is used.

**Comment by mbolding** [comment]
Siemens is coming out to check the GPUs

**Comment by jtotenha** [comment]
Siemens will be back on Friday 5/13 to swap GPUs and see if it makes a difference (swapping entire MARS unit, GPU is part of "imager" which is part of MARS)

**Comment by mbolding** [comment]
talked to Essa Yacoub today about further troubleshooting. will proceed with imager swap and they are looking at possible causes there.  our protocols work on their scanner. It is mysterious that epi bold works and epi dwi does not.

will also try reducing the number of coil elements used

**Comment by mbolding** [comment]
found this in the install package:`eja_checkNVIDIA.sh`
good stuff starting at line 77 :)

```
  # Count the number of NVIDIA controllers found, exit if none
    if [ -e "/sbin/lspci" ]; then
        LSPCI="/sbin/lspci"
...

```

will try it...

@jtotenha yeah we tried lspci, but there is more 

will also try to push the Siemens visit earlier

**Comment by mbolding** [comment]
I logged into mars and ran:  `/usr/bin/nvidia-smi -L`  and it is only listing one GPU.  AFAIK we need 2 to run the multiband DWI

**Comment by mbolding** [comment]
Hi Mark,

Having only 1 GPU could be a problem, if the CMRR sequence identifies that there has 2 GPUs and there is a mismatch. 

Can you look at the file, C:\Medcom\MCIR\Med\Config\eja_hardware.ini . What does the NumberOfGPU field say? And the GPUCompatibility field say in the file. 

To make sure your current problem is a GPU problem or not, you could change both the fields in the file to zero. That way, the sequence will try to run without GPU. 

Do try the above and let us know if it resolved the issue. 

Thanks,
Sudhir

**Comment by mbolding** [comment]
the file says:
`NumberOfGPU = 1`
`GPUCompatibility = 2.0`

setting them to 0 allows the sequence to run.

**Comment by mbolding** [comment]
replace GPUs tomorrow, reboot scanner, check eja_hardware.ini to make sure it says 2 GPUs, then run MB DWI

**Comment by mbolding** [comment]
GPUs were stuck in customs.  they were replaced today.

C:\Medcom\MCIR\Med\Config\eja_hardware.ini now reports 
`NumberOfGPU = 2`
`GPUCompatibility = 2.0`

`/usr/bin/nvidia-smi -L` shows 2 GPUs

**Comment by mbolding** [comment]
New GPUs fixed it
