### ISSUE TITLE
Keys for weekend scanners 

### ISSUE THREAD

**Issue by mbolding** [mbolding/cinl#20]

**Comment by mbolding** [comment]
the keys we have open too many things to give out,  need to rekey the locks

**Comment by MegaRich** [comment]
this includes perimeter access? and keys to equipment room and interview room?

**Comment by mbolding** [comment]
Not perimeter access.  Just doors in the lab

**Comment by jtotenha** [comment]
do we know if UAB would do the door re-keying or the hospital?

**Comment by mbolding** [comment]
I think for now we will get a keypad lock box and keep a key in that. will need to tie the key to the lock box.

labs that can have access so far:
- Younger
- Knight
- Szaflarski

**Comment by jtotenha** [comment]
key is in keypad lockbox tied to research rack, please contact Dr. Bolding or John T for code, remember that lockbox and key are not MR-safe
![image](https://cloud.githubusercontent.com/assets/19213072/16307510/155d00d6-3927-11e6-809d-68a38a1fa89f.png)
![image](https://cloud.githubusercontent.com/assets/19213072/16307516/1a66b7c0-3927-11e6-968a-b0afe487268c.png)
