### ISSUE TITLE
Image Brightness in EPI on 20-channel Coil

### ISSUE THREAD

**Issue by TDeramusMRI** [mbolding/cinl#201]
We recently tested a 3mm isotropic sequence we adapted from the HCP resting in the shared protocols and we noticed some large bright spots near the mid-line in the frontal cortex and in bits of the occipital lobe.

We don't think this looks normal so we were wondering if anyone else has been seeing anything like this, mostly want to know if its our sequence or an equipment issues.

![image](https://cloud.githubusercontent.com/assets/23127333/19819446/4c6c3d6a-9d1a-11e6-8707-d95704e6bdbf.png)

**Comment by mbolding** [comment]
check to see if prescan normalize is on
