### ISSUE TITLE
set up data acq. computer with fMRI stimulus software while presentation computer is being repaired

### ISSUE THREAD

**Issue by jtotenha** [mbolding/cinl#27]
need to download and license Presentation, eye tracker software, directRT, eprime, matlab, etc...

**Comment by MegaRich** [comment]
Stimulus computer is officially repaired as of 5/5/16 (new hard drive) - software needs to be set up

**Comment by jtotenha** [comment]
no longer needed, as presentation/stimulus computer now has a new hard drive #53
