### ISSUE TITLE
hooks to hang all fORP (and other) crap in the scanner room

### ISSUE THREAD

**Issue by mbolding** [mbolding/cinl#44]

**Comment by mbolding** [comment]
order the hooks through bethany

**Comment by jtotenha** [comment]
everything is hung up on labelled hooks as of 6/22, will need to add more hooks as more equipment is installed 
![image](https://cloud.githubusercontent.com/assets/19213072/16319775/36135b30-395a-11e6-8ce9-76158850e8e7.png)
