### ISSUE TITLE
connect o-scope to monitor the gradient waveforms

### ISSUE THREAD

**Issue by mbolding** [mbolding/cinl#45]

**Comment by jtotenha** [comment]
![gradientconnections](https://cloud.githubusercontent.com/assets/19213072/15155402/ee102e6e-16a7-11e6-8f49-e905de64fb9f.jpg)
![gradientconnectionsdescription](https://cloud.githubusercontent.com/assets/19213072/15155405/ef9d01d0-16a7-11e6-94b5-bcc170f51175.jpg)

**Comment by jtotenha** [comment]
there's 2 locations in the gradient cabinet that look promising to plug into the o-scope, X4-6, and X11-13

need to find more information about these, what does Nom. and CAV mean?

**Comment by jtotenha** [comment]
from the functional descriptions, X4-6 are the digital values calculated for the gradients, the "nominal" values, while the X11-X13 are the actual measured current going through the gradient coils, the "actual" current values, so X11-13 are the ones to monitor, need "QLA" connectors, and some very long cables to reach the o-scope

**Comment by mbolding** [comment]
need the long cables from VH
