### ISSUE TITLE
dual link DVI adapter for stimulus MAC

### ISSUE THREAD

**Issue by mbolding** [mbolding/cinl#57]

**Comment by jtotenha** [comment]
$99 from apple: http://www.apple.com/shop/product/MB571LL/A/mini-displayport-to-dual-link-dvi-adapter?fnode=dd41fdab5859399cf4c5a1ede71aed0f62c32cafd54b2ffd685dae37fd42ffd299fd1934c85b90892764b1440902ca4b39e00da3b4bb24cb8dcd91ef0ab1f7210eec7ad37a47cdb45c39ed77d4346380be256e32feda05c5c1ee74e510c9e35e

**Comment by jtotenha** [comment]
![image](https://cloud.githubusercontent.com/assets/19213072/15075143/6f7ed902-1368-11e6-8d0d-533b796c7eba.png)

**Comment by mbolding** [comment]
Asked Bethany to order
