### ISSUE TITLE
shutdown Leo and remove data

### ISSUE THREAD

**Issue by mbolding** [mbolding/cinl#68]

**Comment by jtotenha** [comment]
I'm moving all the data from LEO to DVD backups, and from the Allegra->LEO->DVDs, it is a time-consuming process as LEO and the DVD writer are very old and slow

**Comment by jtotenha** [comment]
All CFNL research data has been archived and removed from the LEO workstation and the Allegra Console, LEO is ready to be moved to Highlands if so desired
