### ISSUE TITLE
Get quote for hifu transducer 

### ISSUE THREAD

**Issue by mbolding** [mbolding/cinl#81]
http://www.sonicconcepts.com/images/pdf/h-108_datasheet.pdf

**Comment by MegaRich** [comment]
is there a particular company you had in mind?

**Comment by mbolding** [comment]
Sonic concepts

**Comment by MegaRich** [comment]
I emailed them for a quote.

**Comment by MegaRich** [comment]
I am emailing Mark with the quote

**Comment by mbolding** [comment]
wow.  that is steep. I hope they are hard to blow up.

Abi is getting more quotes.
