### ISSUE TITLE
find inflatable head pillows for use in tagging experiments

### ISSUE THREAD

**Issue by jtotenha** [mbolding/cinl#95]
pearltec multipad, multipad duo 01

$546, mriequip.com, http://www.mriequip.com/store/pc/viewPrd.asp?idproduct=1530&idcategory=266

$539, newmatic medical, http://www.newmaticmedical.com/positioners/p/MULTIPAD-Positioning-System/

$577, magmedix inc, http://www.magmedix.com/patient-comfort/multipad-duo-for-mri-and-ct.html

![multipad](https://cloud.githubusercontent.com/assets/19213072/15116549/57d86242-15c9-11e6-8bb2-805a111eeb8d.jpg)

**Comment by mbolding** [comment]
please order

**Comment by mbolding** [comment]
saline bags work too. just tried them

**Comment by jtotenha** [comment]
will use saline bags for now
